version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false # Disable SSL for simplicity
    ports:
      - "9200:9200"
    networks:
      - es-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_ELASTICSEARCH_CLIENT_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_CLIENT_ELASTICSEARCH_USERNAME=elastic
      - SPRING_ELASTICSEARCH_CLIENT_ELASTICSEARCH_PASSWORD=changeme
    networks:
      - es-network

networks:
  es-network:
    driver: bridge
