#--------------------------------------------------------------------------------------------------------------------------------------
#      SERVER
#--------------------------------------------------------------------------------------------------------------------------------------

server.port=8077


#--------------------------------------------------------------------------------------------------------------------------------------
#      ELASTIC SEARCH
#--------------------------------------------------------------------------------------------------------------------------------------

spring.elasticsearch.uris=localhost:9200


#--------------------------------------------------------------------------------------------------------------------------------------
