#--------------------------------------------------------------------------------------------------------------------------------------
#      SERVER
#--------------------------------------------------------------------------------------------------------------------------------------

server.port=8077


#--------------------------------------------------------------------------------------------------------------------------------------
#      ELASTIC SEARCH
#--------------------------------------------------------------------------------------------------------------------------------------


#elasticsearch.url=localhost:9200
spring.elasticsearch.uris=localhost:9200
