# ======================== Elasticsearch Configuration =========================

# Set the cluster name
cluster.name: my-cluster

# Set the node name (useful if you run multiple nodes)
node.name: node-1

# Network settings: Set the IP address and port that Elasticsearch will bind to.
network.host: 0.0.0.0
http.port: 9200

# Path settings: Directories where data, logs, and other files are stored
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

# Enable Elasticsearch security features
xpack.security.enabled: true

# Optional: Set the built-in users password (like elastic)
# If using Elastic Cloud, you don't need this, as Cloud manages authentication
bootstrap.password: changeme

# Optional: Disable authentication if not needed (for development environments)
# xpack.security.authc:
#   anonymous:
#     username: anonymous_user
#     roles: superuser
#     authz_exception: false

# Cluster settings: Set the discovery type to single-node for a standalone instance
discovery.type: single-node

# Optional: Enable cross-origin resource sharing (CORS) for external clients
http.cors.enabled: false
http.cors.allow-origin: "*"

# Other settings (optional)
# http.max_content_length: 100mb


xpack.security.transport.ssl.enabled: false
